#!/usr/bin/with-contenv bash

# create folders
# make folders
mkdir -p "${CONFIG}/mylar"
mkdir -p "${CONFIG}/scripts"
mkdir -p "$APP_ROOT"
#maybe should do /mnt and newgroup /folders, but too tired

# install app
if [[ -d "$APP_ROOT/$APPDIRNAME/.git" ]]
then
    cd "$APP_ROOT/$APPDIRNAME"
    git stash
    git checkout $GITBRANCH
    git pull
else
    git clone $GITURL "$APP_ROOT/$APPDIRNAME" -b $GITBRANCH
fi

# copy scripts folder to config
[[ ! -d "${CONFIG}/scripts/sabnzbd" ]] && \
	cp -pr "${APP_ROOT}/${APPDIRNAME}/post-processing/"* "${CONFIG}/scripts/"

# permissions
chown -R abc:abc "${APP_ROOT}"
chown -R abc:abc "${CONFIG}"
